---
- name: Install Postgres.app (Mac)
  homebrew_cask: name=postgres state=present install_options="appdir=/Applications"
  tags: postgres

- name: Add psql config
  copy: src=psqlrc dest=~/.psqlrc
  tags: postgres

- name: Install PostgreSQL pref pane
  homebrew_cask:
    name: postgrespreferencepane
    state: installed
  when: ansible_os_family == 'Darwin'
  tags: postgres
