---
- name: install virtualenv
  command: >
    /usr/local/bin/pip install virtualenv
    creates=/usr/local/bin/virtualenv
  tags: python

- name: Install virtualenvwrapper
  pip: name={{ item }}
  with_items:
    - virtualenvwrapper
  tags: python

- name: Install OpenSSL for Python
  homebrew:
    name: openssl
    state: linked
  tags: python

- name: Tap older Python repo
  homebrew_tap: name=derekkwok/python
  tags: python

- name: Install Python versions
  homebrew: name={{ item }} state=present
  with_items:
    - python
    - python3
    - python33
    - python34
    - pypy
  tags: python

- name: Add pip directory
  file:
    name: ~/.pip
    state: directory
  tags: python

- name: Setup pip configuration
  copy: >
    dest=~/.pip/pip.conf
    src=pip.conf
  tags: python
