---

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest=~/.oh-my-zsh
       recursive=yes
  tags: zsh

- name: Ensure oh-my-zsh-custom directory
  file:
    name: ~/.oh-my-zsh-custom
    state: directory
  tags: zsh

- name: Download custom zsh plugins from git
  ansible.builtin.git: 
    repo: "{{ item.plugin_url }}"
    dest: "{{ zsh_custom_dir }}/plugins/{{ item.plugin_name }}"
  loop:
    - plugin_name: zsh-autosuggestions
      plugin_url: https://github.com/zsh-users/zsh-autosuggestions


- name: Download additional zsh themes
  get_url: 
    url: "{{ item }}"
    dest: "~/.oh-my-zsh/themes/{{ item | basename }}"
  with_items:
    - https://raw.githubusercontent.com/xfanwu/oh-my-zsh-custom-xxf/master/themes/xxf.zsh-theme

- name: add zshrc file
  template: 
    src: zshrc.j2
    dest: ~/.zshrc
  tags: zsh
