---

- name: Add desktop utility tools
  homebrew_cask: name={{ item }} state=present
  with_items:
    - alfred
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add general desktop tools
  homebrew_cask: name={{ item }} state=present
  with_items:
    # - iterm2
    - cyberduck
    # - macpass
  when: ansible_os_family == 'Darwin'
  tags: common
