---

- name: Add browsers
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add desktop utility tools
  homebrew_cask: name={{ item }} state=present
  with_items:
    - dash
    - alfred
    - gpgtools
    - java
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add general desktop tools
  homebrew_cask: name={{ item }} state=present
  with_items:
    - iterm2
    - google-drive
    - send-to-kindle
    - cyberduck
    - macpass
  when: ansible_os_family == 'Darwin'
  tags: common
