---

- import_role: 
    name: homebrew
  when: ansible_os_family == 'Darwin'
  tags: dev

- import_role: 
    name: zsh
  when: ansible_os_family == 'Darwin'
  tags: dev

- import_role: 
    name: common
  when: ansible_os_family == 'Darwin'
  tags: dev

- import_role: 
    name: docker
  when: ansible_os_family == 'Darwin'
  tags: dev

- import_role: 
    name: git
  when: ansible_os_family == 'Darwin'
  tags: dev

- name: install development libraries (Mac)
  homebrew: name={{ item }} state=present
  with_items:
    - libevent
    - libmemcached
    - libxml2
    - libffi
    - gdal
    - gmp
    - mkcert
    - nss
    - bash-completion
    - gh
    - cloc
    - lefthook
    - fnm
    - shfmt
  when: ansible_os_family == 'Darwin'
  tags: dev

- name: Add development desktop tools
  homebrew_cask: name={{ item }} state=present
  with_items:
    - ngrok
    - visual-studio-code
    - raycast
  when: ansible_os_family == 'Darwin'
  tags: dev

- name: Virtualization softwares
  homebrew_cask: name={{ item }} state=present
  with_items:
    - virtualbox
    - vagrant
    # - docker
  when: ansible_os_family == 'Darwin'
  tags: dev

