---

- role: homebrew
  when: ansible_os_family == 'Darwin'
  tags: dev

- role: zsh
  when: ansible_os_family == 'Darwin'
  tags: dev

- role: common
  when: ansible_os_family == 'Darwin'
  tags: dev

- role: docker
  when: ansible_os_family == 'Darwin'
  tags: dev

- role: git
  when: ansible_os_family == 'Darwin'
  tags: dev

- name: install development libraries (Mac)
  homebrew: name={{ item }} state=present
  with_items:
    - libevent
    - libmemcached
    - libxml2
    - libffi
    - gdal
    - gmp
  when: ansible_os_family == 'Darwin'
  tags: dev

- name: Add development desktop tools
  homebrew_cask: name={{ item }} state=present
  with_items:
    - ngrok
    - visual-studio-code-insiders
  when: ansible_os_family == 'Darwin'
  tags: dev

- name: Virtualization softwares
  homebrew_cask: name={{ item }} state=present
  with_items:
    - virtualbox
    - vagrant
    - docker
  when: ansible_os_family == 'Darwin'
  tags: dev

